config/routes.rb
Rails.application.routes.draw do
  resources :clients
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "case_worker", to: "pages#case_worker"
  mount Cfa::Styleguide::Engine => "/cfa"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  require 'open-uri'

  has_one_attached :recording

  after_create :collatoral_contact

  def collatoral_contact
    result = Twilio::REST::Client.new.studio.flows(ENV["TWILIO_STUDIO_FLOW"]).executions.create(
      to: phone,
      from: ENV["TWILIO_PHONE_NUMBER"],
    )
  end

  def update_from_twilio
    twilio = Twilio::REST::Client.new
    recordings = twilio.recordings
    most_recent_recording_sid = recordings.list.sort_by { |r| r.date_created }.last.sid
    recording = "https://api.twilio.com/2010-04-01/Accounts/"+ENV["TWILIO_ACCOUNT_SID"]+"/Recordings/"+most_recent_recording_sid+".mp3"
    self.recording.attach(
        io: open(recording,
                 http_basic_authentication: [ENV["TWILIO_ACCOUNT_SID"], ENV['TWILIO_AUTH_TOKEN']]),
        filename: 'recording.mp3',
        content_type: 'audio/mpeg')

    most_recent_execution_sid = twilio.studio.flows(ENV['TWILIO_STUDIO_FLOW']).executions.list.sort_by{|e| e.date_created}.last.sid
    execution_context = twilio.studio.flows(ENV['TWILIO_STUDIO_FLOW']).executions(most_recent_execution_sid).execution_context.fetch
    transcription = execution_context.context["flow"]["variables"]["transcription"]

    self.update transcription: transcription
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.create(client_params)
    redirect_to client_path(@client.id)
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    @client.update(client_params)

    if @client.calls_done?
      @client.update_from_twilio
    end

    redirect_to @client
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:phone, :transcription, :verified, :calls_done)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/clients/new.html.erb
<div class="page-wrapper">
  <div class="slab">
    <main id="main" class="form-card">
      <header class="form-card__header">
        <h1 class="form-card__title">Jane Doe</h1>
        <h1 class="text--help">Case information</h1>
      </header>

      <div class="form-card__content">
        <div class="grid">
          <div class="grid__item width-one-third">
            <div class="summary-table summary-table--left">
              <span class="label label--red">Unverified</span>
              <p class="summary-table__label">Employment</p>
              <p class="summary-table__value">Walmart</p>
              <p class="summary-table__label">Supervisor Name and Phone</p>
              <p class="summary-table__value">Joe Doe</p>
              <%= form_for @client, url: clients_path, builder: Cfa::Styleguide::CfaFormBuilder do |f| %>
                <%= f.cfa_input_field :phone, 'Phone', classes: ["text-input","form-width--phone"]%>
                <%= f.submit "Send in the robots 🤖", class: ["button"] %>
              <% end %>
            </div>
          </div>
          <div class="grid__item width-one-third">
            <div class="summary-table summary-table--left">
              <span class="label label--red">Unverified</span>
              <p class="summary-table__label">Lost Job</p>
              <p class="summary-table__value">Toys R Us</p>
              <p class="summary-table__label">Supervisor Name and Phone</p>
              <p class="summary-table__value">Jackie Jackson</p>
              <p class="summary-table__value">(555) 555-5555</p>
            </div>
          </div>
          <div class="grid__item width-one-third">
            <div class="summary-table summary-table--left">
              <span class="label label--red">Unverified</span>
              <p class="summary-table__label">Residence</p>
              <p class="summary-table__value">123 Main St</p>
              <p class="summary-table__label">Land Lord</p>
              <p class="summary-table__value">Scrooge McDuck</p>
              <p class="summary-table__value">(555) 555-5555</p>
            </div>
          </div>
        </div>
      </div>

      <div class="form-card__footer">
        <footer class="form-card__button_right">
        </footer>
      </div>
    </main>
  </div>
</div>

app/views/clients/show.html.erb
<div class="page-wrapper">
  <div class="slab">
    <main id="main" class="form-card">
      <header class="form-card__header">
        <h1 class="form-card__title">Jane Doe</h1>
        <h1 class="text--help">Case information</h1>
      </header>

      <div class="form-card__content">
        <div class="grid">
          <div class="grid__item width-one-third">
            <div class="summary-table summary-table--left">
            <% if @client.verified? %>
              <span class="label label--green">Verified</span>
            <% else %>
              <span class="label label--red">Unverified</span>
            <% end %>
              <p class="summary-table__label">Employment</p>
              <p class="summary-table__value">Walmart</p>
              <p class="summary-table__label">Supervisor Name and Phone</p>
              <p class="summary-table__value">Joe Doe</p>
              <p class="summary-table__value"><%= @client.phone %></p>
            </div>
          </div>
          <div class="grid__item width-one-third">
            <div class="summary-table summary-table--left">
              <% if @client.verified? %>
                <span class="label label--green">Verified</span>
              <% else %>
                <span class="label label--red">Unverified</span>
              <% end %>              <p class="summary-table__label">Lost Job</p>
              <p class="summary-table__value">Toys R Us</p>
              <p class="summary-table__label">Supervisor Name and Phone</p>
              <p class="summary-table__value">Jackie Jackson</p>
              <p class="summary-table__value">(555) 555-5555</p>
            </div>
          </div>
          <div class="grid__item width-one-third">
            <div class="summary-table summary-table--left">
              <% if @client.verified? %>
                <span class="label label--green">Verified</span>
              <% else %>
                <span class="label label--red">Unverified</span>
              <% end %>
              <p class="summary-table__label">Residence</p>
              <p class="summary-table__value">123 Main St</p>
              <p class="summary-table__label">Land Lord</p>
              <p class="summary-table__value">Scrooge McDuck</p>
              <p class="summary-table__value">(555) 555-5555</p>
            </div>
          </div>
        </div>
    </div>

      <div class="form-card__footer">
        <footer class="form-card__button_right">
        <% if @client.calls_done? %>
        <div class="summary-table summary-table--left with-padding-large">
          <p class="summary-table__label">Recording</p>
          <p class="summary-table__value">
            <audio controls>
              <source src=<%= url_for(@client.recording) %> type="audio/mpeg">
            </audio>
          </p>
          <p class="summary-table__label">Transcription</p>
          <p class="summary-table__value"><%= @client.transcription %></p>
        </div>

          <%= form_for @client, url: client_path(@client), method: :put, builder: Cfa::Styleguide::CfaFormBuilder do |f| %>
            <%= f.cfa_single_tap_button(:verified, "Verify", true, classes: ["button--primary"]) %>
          <% end %>
        <% else %>
          <%= form_for @client, url: client_path(@client), method: :put, builder: Cfa::Styleguide::CfaFormBuilder do |f| %>
            <%= f.cfa_single_tap_button(:calls_done, "Verification call is complete?", true) %>
          <% end %>
        <% end %>
        </footer>
      </div>
    </main>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CollateralContact</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page-wrapper">
      <header class="main-header">
        <div class="toolbar">
          <div class="toolbar__left">
            <h1 class="main-header__title"><a class="main-header__logo" href="/">Collateral Contact</a></h1>
          </div>
        </div>
      </header>

      <%= yield %>

      <footer class="main-footer">
        <div class="grid">
          <div class="grid__item">
            <p class="text--small">
              Collateral Contact is a service run by <a href="https://www.codeforamerica.org/">Code for America</a>.
            </p>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<section class="slab slab--hero">
  <div class="hero--cta-options">
    <div class="grid">
      <div class="grid__item width-one-half">
        <h1>
          The Verificationator
        </h1>
        <%= link_to new_client_path, class: ["button button--cta"] do %>
          Log In <i class="button__icon icon-arrow_forward"></i>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section class="slab slab--white">
  <div class="grid">
    <div class="grid__item width-one-half">
      <p class="h4">Automatically verify a client's:</p>
      <ul class="list--padded">
        <li><i class="icon-done"></i>Place of employment</li>
        <li><i class="icon-done"></i>Lost jobs</li>
        <li><i class="icon-done"></i>Place of residence</li>
      </ul>
    </div>
    <br/>
    <div class="grid__item width-one-half">
      <%= image_tag "logo-black.png" %>
    </div>
  </div>
</section>